# Markdownlint 配置文件
# 基于项目需求定制的 Markdown 格式规则

# 默认启用所有规则
default: true

# ===========================================
# 禁用的规则列表 (集中管理)
# ===========================================
# 规则说明:
#   MD013: 行长度限制 - 禁用原因: 项目中存在长URL和代码块
#   MD024: 重复标题 - 禁用原因: 文档结构需要重复章节标题
#   MD025: 多个顶级标题 - 禁用原因: 项目文档拆分为多个部分
#   MD029: 有序列表前缀 - 禁用原因: 项目使用自定义编号方案
#   MD033: 内联HTML - 禁用原因: 某些情况下需要HTML标签
#   MD036: 强调代替标题 - 禁用原因: 文档中使用强调作为视觉分隔符
#   MD040: 代码块语言 - 禁用原因: 项目中有通用代码块无需指定语言
#   MD041: 第一行标题 - 禁用原因: 某些文档可能以其他内容开头
#   MD046: 代码块类型限制 - 禁用原因: 支持多种代码块格式

MD013: false # 行长度限制
MD024: false # 重复标题
MD025: false # 多个顶级标题
MD029: false # 有序列表前缀
MD033: false # 内联HTML
MD036: false # 强调代替标题
MD040: false # 代码块语言
MD041: false # 第一行标题
MD046: false # 代码块类型限制

# ===========================================
# 启用的规则自定义配置
# ===========================================

MD007:
  # 无序列表缩进
  indent: 2

MD004:
  # 无序列表样式统一使用星号
  style: "asterisk"

MD022:
  # 标题周围空行
  lines_above: 1
  lines_below: 1

MD032:
  # 列表周围空行
  lines_above: 1
  lines_below: 1

MD012:
  # 禁止多个连续空行
  maximum: 1
